### ISSUE TITLE
Can't pull image from private registry

### ISSUE THREAD

**Issue by pfandzelter** [mdubourg001/glci#25]
Hi, thanks for the project!
I'm running on macOS and I think I'm hitting an error pulling the Docker image for my CI. I've tried pulling the image manually but it didn't help. Here's the error I'm running into:

```
$ glci
---------------------------------------------------
Running job "golint" for stage "analysis"
---------------------------------------------------

/Users/tobias/.config/yarn/global/node_modules/docker-modem/lib/modem.js:383
  stream.on('data', onStreamEvent);
         ^

TypeError: Cannot read property 'on' of null
    at Modem.followProgress (/Users/tobias/.config/yarn/global/node_modules/docker-modem/lib/modem.js:383:10)
    at /Users/tobias/.config/yarn/global/node_modules/glci/dist/cli.min.js:324:24
    at /Users/tobias/.config/yarn/global/node_modules/dockerode/lib/docker.js:116:7
    at /Users/tobias/.config/yarn/global/node_modules/docker-modem/lib/modem.js:309:7
    at IncomingMessage.<anonymous> (/Users/tobias/.config/yarn/global/node_modules/docker-modem/lib/modem.js:328:9)
    at IncomingMessage.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

$ glci --version
0.1.0
```

The Docker image is hosted on a private repository, but I'm logged in locally.

**Comment by mdubourg001** [comment]
glci uses Dockerode to drive the Docker engine, and more precisely the `docker.pull` method to pull images from Docker registry. This function accepts an object for authentication but does not automatically detects if you are already logged locally...

I just have to figure out an API to allow providing authentication options to glci, in order to authenticate to private registries. An option could be a config file to put in `.glci/glci.json`, or an CLI arg accepting an `IdentityToken`.

I renamed the issue title to be more acurate to the actual problem.

Thank you for reporting this, really helpful ! 👌

**Comment by pfandzelter** [comment]
@mdubourg001 Thanks for the quick response, that makes perfect sense. Weird that authentication isn't managed by the Docker daemon... For now, I've added a `return` if pulling the image fails for whatever reason (private repo, no network connection, etc.) in #26. The resulting error message is probably a bit more user friendly

**Comment by mdubourg001** [comment]
Just merged the PR, thx ! 👍 

Will keep this thread updated when I'll do some work on this subject.

**Comment by mdubourg001** [comment]
I finally figured out GitLab CI itself relies on a environment variable (`DOCKER_AUTH_CONFIG`) to handle authentication on private registries, so I went with the same solution (the variable is to put inside your root `.env` file, that is automatically red by gcli). 

The feature was released in https://github.com/mdubourg001/glci/releases/tag/v0.3.0 👌
